<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ICPL11605" name="com.infoStretch.Infostretch.MultiBrowser" tests="2" failures="0" timestamp="25 Jan 2018 11:02:28 GMT" time="0.013" errors="1">
  <testcase name="flipkartlogin" time="0.008" classname="com.infoStretch.Infostretch.MultiBrowser"/>
  <testcase name="flipkartlogin" time="0.005" classname="com.infoStretch.Infostretch.MultiBrowser">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.infoStretch.Infostretch.MultiBrowser.closeBrowser(MultiBrowser.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.TestRunner.afterRun(TestRunner.java:1019)
	at org.testng.TestRunner.run(TestRunner.java:625)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- flipkartlogin -->
</testsuite> <!-- com.infoStretch.Infostretch.MultiBrowser -->
